# =============================================
#   arise - Hyprland config
#   by ByLouiz
# =============================================

# ── MONITOR ──────────────────────────────────
monitor=eDP-1,1920x1080@60,0x0,1

# ── VARIABLES ────────────────────────────────
$terminal = kitty
$menu     = rofi -show drun
$browser  = zen-browser
$editor   = code
$files    = thunar

# ── ENVIRONMENT ──────────────────────────────
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# ── AUTOSTART ────────────────────────────────
exec-once = qs -c serafin
exec-once = mpvpaper -o "no-audio loop-file=inf image-display-duration=inf hwdec=auto input-ipc-server=/tmp/serafin-mpv.sock" '*' /home/arise/.config/serafin/current-wallpaper

exec-once = dunst

# ── APARIENCIA ───────────────────────────────
general {
    gaps_in          = 8
    gaps_out         = 12
    border_size      = 1
    col.active_border   = rgba(89b4faff) rgba(74c7ecff) 45deg
    col.inactive_border = rgba(1e1e2eaa)
    resize_on_border = true
    layout           = dwindle
}

decoration {
    rounding = 25

    blur {
        enabled  = true
        size     = 6
        passes   = 2
        vibrancy = 0.1696
    }

    shadow {
        enabled = true
        range   = 8
        color   = rgba(1a1a2eee)
    }
}

animations {
    enabled = true

    bezier = smooth, 0.05, 0.9, 0.1, 1.05

    animation = windows,    1, 4, smooth
    animation = windowsOut, 1, 4, default
    animation = border,     1, 5, default
    animation = fade,       1, 5, default
    animation = workspaces, 1, 4, smooth, slidevert
}

input {
    kb_layout    = us
    kb_variant   = intl
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

dwindle {
    preserve_split = true
}

# ── KEYBINDS ─────────────────────────────────
$mod = SUPER

# Apps
bind = $mod, Q, exec, $terminal
bind = $mod, W, exec, $browser
bind = $mod, C, exec, $editor
bind = $mod, E, exec, $files
bind = $mod SHIFT, W, exec, qs -c serafin ipc call wallpaper toggle




# Ventanas
bind = $mod, A,         killactive
bind = $mod, F,         fullscreen
bind = $mod, Space,     togglefloating
bind = $mod, P,         pseudo

# Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

bind = $mod, X, workspace, +1
bind = $mod, Z, workspace, -1

# Sistema
bind = $mod, L, exec, hyprlock
bind = $mod, M, exit

# Screenshot
bind = $mod, S, exec, grimblast --notify copysave area | satty --filename -

# Mouse drag/resize
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Volumen (botones mouse)
#bindm = $mod, mouse:276, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+
#bindm = $mod, mouse:275, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
#bindm = $mod, mouse:274, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Multimedia keys
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = ,XF86AudioMute,        exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86MonBrightnessUp,  exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown,exec, brightnessctl -e4 -n2 set 5%-
